import type { Module, Question } from '../types';

/** Módulo completo de Helm: 9 lições, cada uma com simulador próprio e quiz de 10 perguntas. */

const files = import.meta.glob('./helm/*.md', { query: '?raw', import: 'default', eager: true }) as Record<string, string>;
const md = (slug: string) => {
  const c = files[`./helm/${slug}.md`];
  if (!c) throw new Error(`Conteúdo não encontrado: helm/${slug}`);
  return c;
};
const q = (q: string, options: string[], answer: number, explanation: string): Question => ({ q, options, answer, explanation });

export const helmModule: Module = {
  id: 'helm',
  title: 'Helm do zero à produção',
  description: 'Curso completo: charts, values, templates, helpers, dependências, hooks, repositórios OCI e operação em produção.',
  level: 'Avançado',
  emoji: '⎈',
  lessons: [
    {
      slug: 'introducao',
      title: 'Helm: conceitos e ciclo de vida',
      summary: 'Chart, values, release e revisão; install, upgrade, rollback e uninstall.',
      minutes: 14,
      content: md('introducao'),
      simulator: 'helm-release',
      quiz: [
        q('O que é uma release no Helm?', ['Um arquivo .tgz do chart', 'Uma instalação de um chart no cluster, com nome e histórico de revisões', 'Uma versão do Kubernetes', 'Um repositório de charts'], 1, 'O mesmo chart pode gerar várias releases (loja-staging, loja-prod).'),
        q('Qual o nome do Secret que guarda a revisão 3 da release loja?', ['helm-loja-3', 'sh.helm.release.v1.loja.v3', 'loja.release.3', 'release-loja-v3'], 1, 'Cada revisão é um Secret com manifesto, values e chart comprimidos, no namespace da release.'),
        q('Qual a principal mudança de arquitetura do Helm 2 para o Helm 3?', ['Charts passaram a ser JSON', 'O Tiller foi removido: o helm usa as credenciais e o RBAC do próprio usuário', 'Releases passaram a ser globais', 'O Helm passou a exigir Kustomize'], 1, 'Sem um servidor com permissões amplas no cluster.'),
        q('Você fez rollback da revisão 5 para a 3. Qual o número da nova revisão?', ['3', '4', '6', 'Nenhum: o histórico é reescrito'], 2, 'Rollback cria uma revisão nova (6) com o conteúdo da 3.'),
        q('Por que helm upgrade --install é preferido em pipelines?', ['É mais rápido', 'É idempotente: instala se não existe e atualiza se existe', 'Ignora erros', 'Não cria histórico'], 1, 'O mesmo comando funciona no primeiro e nos demais deploys.'),
        q('O que faz --atomic?', ['Aplica recursos um por vez', 'Se a operação falhar, desfaz automaticamente (rollback no upgrade, uninstall no install)', 'Criptografa os values', 'Impede outros upgrades para sempre'], 1, 'Implica --wait: só é sucesso se os recursos ficarem prontos.'),
        q('Um upgrade falhou sem --atomic. Como fica o histórico?', ['A revisão nova fica failed e a anterior continua deployed', 'Todas ficam failed', 'A release é apagada', 'O Helm faz rollback sozinho'], 0, 'Os recursos podem estar parcialmente atualizados; investigue e corrija ou faça rollback.'),
        q('Qual comando mostra os values efetivos (incluindo os padrões do chart) de uma release?', ['helm get values <release> --all', 'helm show values <release>', 'helm status <release>', 'helm values <release>'], 0, 'Sem --all, mostra só os values que você passou.'),
        q('Releases do Helm têm escopo de…', ['Cluster', 'Namespace', 'Nó', 'Contexto do kubeconfig'], 1, 'O mesmo nome de release pode existir em namespaces diferentes.'),
        q('O que o status pending-upgrade persistente indica?', ['Upgrade agendado para depois', 'Um upgrade que começou e foi interrompido (ou ainda está rodando); ele bloqueia novas operações', 'Que falta aprovação manual', 'Que a release foi desinstalada'], 1, 'Resolva com helm rollback para a última revisão boa.'),
      ],
    },
    {
      slug: 'anatomia-chart',
      title: 'Anatomia de um chart',
      summary: 'Chart.yaml, version × appVersion, templates, crds, schema e helm lint.',
      minutes: 12,
      content: md('anatomia-chart'),
      simulator: 'helm-lint',
      quiz: [
        q('Qual apiVersion do Chart.yaml os charts do Helm 3+ usam?', ['v1', 'v2', 'apps/v1', 'helm.sh/v3'], 1, 'v1 era o formato do Helm 2.'),
        q('Qual a diferença entre version e appVersion?', ['São sinônimos', 'version é a versão do chart (SemVer); appVersion é a versão da aplicação empacotada', 'appVersion é obrigatória e version opcional', 'version é a versão do Kubernetes'], 1, 'Mudou qualquer coisa no chart → incremente version.'),
        q('Você mudou só um template do chart. O que deve mudar no Chart.yaml?', ['Nada', 'version (um patch ou minor, conforme a mudança)', 'appVersion', 'name'], 1, 'Versões de chart devem ser imutáveis: conteúdo novo, versão nova.'),
        q('O que acontece com arquivos em templates/ cujo nome começa com _?', ['São ignorados totalmente', 'Não geram manifestos, mas seus define ficam disponíveis', 'São aplicados primeiro', 'Viram hooks'], 1, 'Por isso os helpers ficam em _helpers.tpl.'),
        q('Para que serve o values.schema.json?', ['Documentar o README', 'Validar os values em install, upgrade, lint e template', 'Gerar os templates', 'Criptografar values'], 1, 'Erros de tipo aparecem antes de chegar ao cluster.'),
        q('Como o Helm trata CRDs no diretório crds/?', ['Atualiza a cada upgrade', 'Instala na primeira instalação, mas não atualiza nem remove', 'Remove no uninstall', 'Ignora sempre'], 1, 'Decisão deliberada para não apagar dados de recursos customizados.'),
        q('O que é um chart do tipo library?', ['Um chart com muitos recursos', 'Um chart só com templates nomeados, para ser usado como dependência; não pode ser instalado sozinho', 'Um chart de banco de dados', 'Um chart sem values'], 1, 'Ótimo para padronizar labels e probes entre muitos serviços.'),
        q('Para que serve o NOTES.txt?', ['Changelog do chart', 'Texto (também templatizado) exibido após install/upgrade', 'Licença', 'Lista de values'], 1, 'Mostre URLs de acesso e próximos passos.'),
        q('O que o helm lint verifica?', ['Só o Chart.yaml', 'Chart.yaml, renderização dos templates, YAML resultante, schema e regras de nome', 'A conexão com o cluster', 'Vulnerabilidades das imagens'], 1, 'Rode com os values de cada ambiente.'),
        q('Qual comando cria um chart inicial completo?', ['helm init loja', 'helm create loja', 'helm new loja', 'helm scaffold loja'], 1, 'Gera Chart.yaml, values, templates, helpers e um teste.'),
      ],
    },
    {
      slug: 'values',
      title: 'Values e precedência',
      summary: 'Camadas de values, merge de mapas e listas, --set e seus tipos, null e globals.',
      minutes: 14,
      content: md('values'),
      simulator: 'helm-values',
      quiz: [
        q('Ordem de precedência (do menor para o maior)?', ['--set < -f < values.yaml', 'values.yaml do chart < arquivos -f (na ordem) < --set', '-f < values.yaml < --set', 'Todos têm o mesmo peso'], 1, 'Entre vários -f, o último vence.'),
        q('O padrão tem env com 3 itens e values-prod.yaml define env com 1 item. Resultado?', ['4 itens', '3 itens', 'Só o 1 item de prod: listas são substituídas', 'Erro'], 2, 'Listas não se mesclam. Prefira modelar como mapa.'),
        q('Como remover uma chave que vem do values.yaml do chart?', ['Com string vazia', 'Definindo-a como null', 'Com --unset', 'Não é possível'], 1, 'null remove a chave herdada no merge.'),
        q('No values.yaml, tag: 1.10. O que o template imprime?', ['1.10', '1.1', '"1.10"', 'Erro'], 1, 'Números de arquivos YAML viram float64. Use aspas: tag: "1.10".'),
        q('No values.yaml, build: 20240501. Como aparece em {{ .Values.build }}?', ['20240501', '2.0240501e+07', '"20240501"', 'Erro'], 1, 'float64 grande é impresso em notação científica pelo Go.'),
        q('Qual flag garante que o valor seja tratado como string?', ['--set', '--set-string', '--set-json', '--values'], 1, 'Ideal para tags, versões e códigos com zeros à esquerda.'),
        q('Como setar o host do primeiro item de uma lista pelo --set?', ['--set ingress.hosts.0.host=a', '--set ingress.hosts[0].host=a', '--set ingress.hosts(0).host=a', 'Não é possível'], 1, 'Índices usam colchetes.'),
        q('Mapas vindos de camadas diferentes são…', ['Substituídos inteiros', 'Mesclados chave a chave, recursivamente', 'Concatenados como listas', 'Ignorados'], 1, 'Só listas e escalares são substituídos.'),
        q('Qual o risco do --reuse-values ao trocar a versão do chart?', ['Nenhum', 'Ele reaproveita os values antigos e ignora novos padrões do chart, podendo gerar configuração incompleta', 'Apaga a release', 'Duplica recursos'], 1, 'Em pipelines, passe todos os arquivos de values explicitamente.'),
        q('Values em global: são visíveis onde?', ['Só no chart pai', 'No pai e em todos os subcharts, como .Values.global', 'Só nos subcharts', 'Em nenhum template'], 1, 'Útil para registry, domínio e labels comuns.'),
      ],
    },
    {
      slug: 'templates',
      title: 'Templates: Go templates e Sprig',
      summary: 'Objetos, pipelines, funções, if/with/range, escopo com $, espaços e depuração.',
      minutes: 18,
      content: md('templates'),
      simulator: 'helm-template',
      quiz: [
        q('Em {{ .Values.tag | default "latest" }}, qual o papel do |?', ['OU lógico', 'Passa o valor à esquerda como último argumento da função à direita', 'Concatena strings', 'Comentário'], 1, 'Equivale a default "latest" .Values.tag.'),
        q('Dentro de {{ with .Values.image }}, como acessar o nome da release?', ['.Release.Name', '$.Release.Name', '..Release.Name', 'Não é possível'], 1, 'with muda o ponto; $ sempre aponta para a raiz.'),
        q('O que {{- faz?', ['Comenta a linha', 'Remove espaços e quebras de linha à esquerda da ação', 'Nega a expressão', 'Indenta'], 1, '-}} remove à direita.'),
        q('Qual a forma segura de inserir um bloco YAML de resources?', ['resources: {{ toYaml .Values.resources }}', 'resources:\\n  {{- toYaml .Values.resources | nindent 2 }}', 'resources: {{ .Values.resources }}', 'resources: {{ quote .Values.resources }}'], 1, 'Sem toYaml, o Go imprime map[...]; com indent na mesma linha, o YAML quebra.'),
        q('Erro "nil pointer evaluating interface {}.tag". Causa provável?', ['Tag com aspas', 'Acessou .Values.image.tag, mas .Values.image não existe', 'Falta de CPU', 'Chart sem versão'], 1, 'Garanta o mapa no values.yaml ou proteja com with/default dict.'),
        q('Qual função interrompe o render com mensagem se o valor estiver vazio?', ['default', 'required', 'empty', 'fail'], 1, 'fail interrompe incondicionalmente (use dentro de um if).'),
        q('Qual a diferença entre include e template?', ['Nenhuma', 'include retorna string e pode ser usado em pipeline; template escreve direto e não pode', 'template é mais novo', 'include só funciona em _helpers.tpl'], 1, 'Por isso usamos include "x" . | nindent 4.'),
        q('Como renderizar localmente sem instalar nada?', ['helm install --local', 'helm template loja ./loja -f values.yaml', 'helm render', 'kubectl helm'], 1, 'Use --debug para ver YAML inválido e -s para um arquivo só.'),
        q('printf "%d" .Values.port imprime %!d(float64=8080). Como corrigir?', ['Usar %s', 'printf "%d" (int .Values.port)', 'Colocar port entre aspas no template', 'Não tem correção'], 1, 'Números de values são float64; int converte.'),
        q('O que lookup retorna durante helm template?', ['O objeto real do cluster', 'Vazio, pois não há conexão com o cluster', 'Um erro sempre', 'O valor do values.yaml'], 1, 'Escreva templates que funcionem com o resultado vazio.'),
      ],
    },
    {
      slug: 'helpers-e-labels',
      title: 'Helpers, nomes e labels',
      summary: 'define/include, fullname e o limite de 63, labels recomendados, selector imutável e checksum.',
      minutes: 12,
      content: md('helpers-e-labels'),
      simulator: 'helm-helpers',
      quiz: [
        q('Por que o helper fullname usa trunc 63?', ['Por estética', 'Nomes de Services e labels são DNS labels com no máximo 63 caracteres', 'Limite do Helm', 'Limite do etcd'], 1, 'Nomes maiores são rejeitados pelo API server.'),
        q('Para que serve o trimSuffix "-" depois do trunc?', ['Remover espaços', 'Evitar que o nome cortado termine em hífen, o que é inválido', 'Adicionar sufixo', 'Nada'], 1, 'DNS labels precisam terminar com caractere alfanumérico.'),
        q('Release pagamentos-api e chart pagamentos-api. Qual o fullname padrão?', ['pagamentos-api-pagamentos-api', 'pagamentos-api', 'api', 'release-pagamentos-api'], 1, 'Se o release já contém o nome do chart, ele não é repetido.'),
        q('Por que os nomes de define devem ter prefixo (loja.labels)?', ['Convenção sem efeito', 'Nomes de templates são globais entre chart e subcharts; sem prefixo, colidem', 'O Helm exige', 'Para ordenar'], 1, 'Dois charts definindo "labels" sobrescrevem um ao outro.'),
        q('Quais labels devem estar no selector de um Deployment?', ['Todos, inclusive version e helm.sh/chart', 'Somente labels estáveis, como app.kubernetes.io/name e instance', 'Nenhum', 'Só helm.sh/chart'], 1, 'O selector é imutável; labels que mudam quebram o upgrade.'),
        q('O ConfigMap mudou num upgrade, mas os Pods (que leem via env) não reiniciaram. Solução clássica?', ['Apagar o namespace', 'Annotation checksum/config com o sha256 do ConfigMap no template do Pod', 'Aumentar réplicas', 'Usar --force'], 1, 'Mudou o hash, mudou o template do Pod, acontece o rolling update.'),
        q('O que {{ tpl .Values.host . }} permite?', ['Criptografar', 'Que o usuário escreva templates dentro dos values', 'Ler arquivos', 'Chamar a API'], 1, 'Ex.: host: "{{ .Release.Name }}.exemplo.com" nos values.'),
        q('Qual o valor típico do label app.kubernetes.io/managed-by em charts?', ['kubectl', 'Helm (via .Release.Service)', 'Argo', 'root'], 1, 'Identifica quem gerencia o objeto.'),
        q('O que acontece com include "loja.labels" (sem o ponto)?', ['Funciona igual', 'O template recebe nil como contexto e falha ou renderiza vazio', 'Usa o contexto raiz automaticamente', 'Erro de sintaxe sempre'], 1, 'O segundo argumento é o contexto: passe ., $ ou um dict.'),
        q('Para que serve fullnameOverride?', ['Mudar o nome do chart', 'Definir o nome completo dos recursos, ignorando a combinação release-chart', 'Mudar o namespace', 'Mudar a versão'], 1, 'nameOverride troca só a parte do chart.'),
      ],
    },
    {
      slug: 'dependencias',
      title: 'Dependências e subcharts',
      summary: 'Chart.yaml dependencies, update × build, condition, tags, alias, escopo de values e globals.',
      minutes: 12,
      content: md('dependencias'),
      simulator: 'helm-dependencies',
      quiz: [
        q('Qual a diferença entre helm dependency update e build?', ['Nenhuma', 'update resolve restrições e atualiza o Chart.lock; build baixa exatamente o que está no lock', 'build publica o chart', 'update apaga dependências'], 1, 'No CI, use build para reprodutibilidade.'),
        q('O que deve ser versionado no Git?', ['Só charts/', 'Chart.yaml e Chart.lock (charts/ costuma ser gerado no CI)', 'Nada', 'Só os .tgz'], 1, 'O lock garante as mesmas versões em todo lugar.'),
        q('condition e tags definidos para a mesma dependência. Quem decide?', ['tags', 'condition, se o caminho existir nos values', 'O que vier primeiro no arquivo', 'Os dois precisam ser true'], 1, 'Condition tem prioridade sobre tags.'),
        q('Como instalar o mesmo chart duas vezes como dependência?', ['Não é possível', 'Com alias diferentes (ex.: api e worker)', 'Com dois Chart.yaml', 'Com --set'], 1, 'Cada alias recebe sua própria seção de values.'),
        q('O que o subchart postgresql enxerga em .Values?', ['Todos os values do pai', 'Seus padrões mesclados com a seção postgresql do pai, mais .Values.global', 'Só .Values.global', 'Nada do pai'], 1, 'O escopo é limitado de propósito.'),
        q('Erro "found in Chart.yaml, but missing in charts/ directory". Como resolver?', ['helm repo update', 'helm dependency build (ou update)', 'Apagar o Chart.lock', 'helm lint'], 1, 'As dependências precisam estar em charts/ antes do install.'),
        q('Como o chart pai costuma referenciar o Service do subchart postgresql?', ['postgresql', '<release>-postgresql, conforme o helper do subchart', 'db', 'kube-postgresql'], 1, 'Documente, pois fullnameOverride do subchart muda o nome.'),
        q('Para que serve um umbrella chart?', ['Criptografia', 'Agrupar várias dependências para instalar um sistema inteiro com uma release', 'Substituir o Kubernetes', 'Testar charts'], 1, 'Troca simplicidade por um histórico e upgrades agregados.'),
        q('Qual repository aponta para um chart local?', ['local://../app', 'file://../app', 'path:../app', '../app'], 1, 'Útil em monorepos.'),
        q('O que faz import-values?', ['Importa arquivos YAML', 'Traz values exportados pelo subchart para o escopo do pai', 'Importa CRDs', 'Baixa dependências'], 1, 'Pouco usado, mas útil com library/subcharts que expõem configurações.'),
      ],
    },
    {
      slug: 'hooks-e-testes',
      title: 'Hooks e testes',
      summary: 'Eventos, pesos, políticas de deleção, falhas, recursos que sobram e helm test.',
      minutes: 13,
      content: md('hooks-e-testes'),
      simulator: 'helm-hooks',
      quiz: [
        q('Qual hook usar para migrar o banco antes de atualizar a aplicação?', ['post-upgrade', 'pre-upgrade (e pre-install)', 'test', 'pre-delete'], 1, 'Assim a nova versão já encontra o schema atualizado.'),
        q('Como os hooks de uma mesma fase são ordenados?', ['Aleatoriamente', 'Por helm.sh/hook-weight (menor primeiro), depois por tipo e nome', 'Pela ordem dos arquivos', 'Por data'], 1, 'Pesos podem ser negativos.'),
        q('Qual política de deleção vale quando a annotation não é informada?', ['hook-succeeded', 'before-hook-creation', 'hook-failed', 'Nenhuma: o hook nunca é apagado'], 1, 'O recurso anterior é apagado antes de criar o novo.'),
        q('Com só hook-succeeded, a migração falha e depois você tenta de novo. O que acontece?', ['Funciona', 'Erro: jobs.batch "…" already exists, porque o Job falho ficou no cluster', 'O Helm renomeia o Job', 'O cluster apaga o Job'], 1, 'Inclua before-hook-creation.'),
        q('Um hook pre-upgrade falha. Os recursos do chart foram atualizados?', ['Sim', 'Não: a operação para antes de aplicá-los, e a release fica failed', 'Parcialmente, sempre', 'Só o Deployment'], 1, 'Em post-*, os recursos já teriam sido aplicados.'),
        q('helm uninstall remove os Jobs de hook?', ['Sempre', 'Não: hooks não fazem parte da release; só uma política de deleção os remove', 'Só em namespaces default', 'Só com --force'], 1, 'Sem política, hooks acumulam no cluster.'),
        q('O que faz a annotation helm.sh/resource-policy: keep?', ['Protege contra edição', 'Faz o Helm não apagar o recurso no uninstall', 'Mantém o recurso em cache', 'Impede upgrades'], 1, 'Útil para PVCs e Secrets com dados.'),
        q('Como executar os testes de uma release?', ['helm lint', 'helm test <release>', 'kubectl test', 'helm verify'], 1, 'Use --logs para ver a saída dos Pods de teste.'),
        q('Por que definir backoffLimit e activeDeadlineSeconds em Jobs de hook?', ['Não é necessário', 'Um Job preso segura o deploy até o --timeout; limites explícitos falham rápido', 'Para o HPA', 'Para economizar disco'], 1, 'Falhar rápido é melhor que esperar 5 minutos.'),
        q('O rollback do Helm desfaz uma migração de banco feita por hook?', ['Sim, automaticamente', 'Não: migrações devem ser compatíveis com a versão anterior (e idempotentes)', 'Só com --atomic', 'Só em PostgreSQL'], 1, 'O Helm reverte manifestos, não dados.'),
      ],
    },
    {
      slug: 'repositorios-e-versoes',
      title: 'Repositórios, OCI e versões',
      summary: 'Repos HTTP e OCI, SemVer e restrições, Chart.lock, assinatura e testes no CI.',
      minutes: 12,
      content: md('repositorios-e-versoes'),
      simulator: 'helm-semver',
      quiz: [
        q('O que um repositório HTTP clássico precisa ter?', ['Um banco de dados', 'Um index.yaml com os charts e versões, mais os .tgz', 'Um cluster Kubernetes', 'Um Dockerfile'], 1, 'helm repo index gera o index.yaml.'),
        q('Como instalar um chart de um registry OCI?', ['helm repo add oci', 'helm install loja oci://registry.exemplo.com/charts/loja --version 1.4.0', 'docker pull loja', 'kubectl apply oci://'], 1, 'Com OCI não é preciso helm repo add.'),
        q('~1.4.0 significa…', ['>=1.4.0 <2.0.0', '>=1.4.0 <1.5.0', 'Exatamente 1.4.0', '<1.4.0'], 1, 'Til permite só patches.'),
        q('^1.4.0 significa…', ['>=1.4.0 <1.5.0', '>=1.4.0 <2.0.0', '>=1.0.0', 'Qualquer versão'], 1, 'Circunflexo aceita tudo compatível dentro do major.'),
        q('^0.4.0 significa…', ['>=0.4.0 <1.0.0', '>=0.4.0 <0.5.0', '>=0.0.0', '0.4.x ou 1.x'], 1, 'Em 0.x, o minor é tratado como mudança incompatível.'),
        q('As versões 16.1.0-rc.1 e 16.0.6 existem. Qual ^16.0.0 escolhe?', ['16.1.0-rc.1', '16.0.6', 'Nenhuma', 'As duas'], 1, 'Prereleases só entram se a restrição tiver prerelease.'),
        q('Qual versão o Helm escolhe entre as que satisfazem a restrição?', ['A menor', 'A maior', 'A mais antiga publicada', 'A primeira do index'], 1, 'E grava a versão exata no Chart.lock.'),
        q('Por que nunca republicar a mesma versão de chart com outro conteúdo?', ['O Helm bloqueia', 'Quebra locks, caches e a reprodutibilidade dos deploys', 'Aumenta o tamanho do repositório', 'Não há problema'], 1, 'Versões de artefato são imutáveis.'),
        q('Para que serve o kubeconform no CI de charts?', ['Formatar YAML', 'Validar o YAML renderizado contra os schemas do Kubernetes', 'Publicar charts', 'Assinar charts'], 1, 'Combine com helm template.'),
        q('Como assinar e verificar charts?', ['Com base64', 'Provenance PGP (helm package --sign / install --verify) ou cosign para charts OCI', 'Com um ConfigMap', 'Não é possível'], 1, 'Políticas de admission podem exigir assinaturas.'),
      ],
    },
    {
      slug: 'producao',
      title: 'Helm em produção',
      summary: 'Three-way merge e drift, HPA, upgrades seguros, CRDs, segredos, GitOps e checklist.',
      minutes: 15,
      content: md('producao'),
      simulator: 'helm-upgrade',
      quiz: [
        q('Alguém mudou a imagem com kubectl set image. No próximo helm upgrade (chart com a imagem antiga), o que acontece?', ['A mudança manual é mantida', 'O Helm impõe a imagem do chart, desfazendo o hotfix', 'O upgrade falha', 'O Helm pergunta'], 1, 'No three-way merge, o que o chart declara vence.'),
        q('Um sidecar injetado pelo service mesh (não declarado no chart) sobrevive ao upgrade?', ['Não', 'Sim: campos que o chart nunca declarou são preservados', 'Só com --force', 'Só no Helm 2'], 1, 'O merge considera o estado live.'),
        q('O chart define replicas: 2 e há HPA. O que acontece a cada deploy?', ['Nada', 'O Deployment volta para 2 réplicas e o HPA precisa escalar de novo', 'O HPA é apagado', 'O upgrade falha'], 1, 'Não renderize replicas quando autoscaling estiver ligado.'),
        q('Para que serve o plugin helm-diff?', ['Comparar charts de repositórios', 'Mostrar o que um upgrade vai mudar no cluster antes de aplicá-lo', 'Fazer rollback', 'Validar schemas'], 1, 'helm diff upgrade loja ./loja -f values-prod.yaml.'),
        q('Dois jobs de CI rodam helm upgrade na mesma release ao mesmo tempo. Resultado típico?', ['Os dois funcionam', 'Um deles falha com "another operation (install/upgrade/rollback) is in progress"', 'O cluster trava', 'A release é duplicada'], 1, 'Serialize deploys por release no CI.'),
        q('Como o Argo CD usa charts do Helm?', ['Cria releases do Helm normalmente', 'Renderiza com helm template e aplica; helm list não mostra essas releases', 'Não suporta Helm', 'Converte para Kustomize'], 1, 'O Flux HelmRelease, por outro lado, cria releases reais.'),
        q('Qual a forma recomendada de lidar com segredos em charts?', ['Values em texto puro no Git', 'External Secrets/CSI ou values criptografados com SOPS (helm-secrets)', 'Colocar no NOTES.txt', 'Em annotations'], 1, 'Lembre que os values de cada revisão ficam num Secret do namespace.'),
        q('Por que CRDs costumam ficar fora do diretório crds/ em produção?', ['São grandes demais', 'Porque o Helm não atualiza CRDs de crds/ em upgrades', 'Porque o Kubernetes proíbe', 'Por causa do RBAC'], 1, 'Chart separado ou aplicação no pipeline resolvem.'),
        q('Para que serve --post-renderer?', ['Gerar documentação', 'Passar o YAML renderizado por outro programa (ex.: Kustomize) antes de aplicar', 'Renderizar mais rápido', 'Assinar o chart'], 1, 'Ajusta charts de terceiros sem fork.'),
        q('O que o helmfile oferece?', ['Um novo formato de chart', 'Declarar várias releases, values e ambientes num arquivo, com diff e apply', 'Um registry', 'Um substituto do kubectl'], 1, 'helmfile diff / helmfile apply.'),
      ],
    },
  ],
};
