// Generated by pnpm --filter @jack-academy/web catalog. Do not edit by hand.
export const learningCatalog = {
  "modules": [
    {
      "id": "containers",
      "title": "Pré-requisito: Containers (Docker)",
      "lessons": [
        {
          "key": "containers/o-que-sao-containers",
          "title": "O que são containers (e o que o Docker faz)"
        },
        {
          "key": "containers/imagens-e-registries",
          "title": "Imagens, tags, digests e registries"
        },
        {
          "key": "containers/executando-containers",
          "title": "Executando containers: ciclo de vida, logs e sinais"
        },
        {
          "key": "containers/dockerfile",
          "title": "Dockerfile: construindo imagens"
        },
        {
          "key": "containers/builds-otimizados",
          "title": "Builds otimizados: multi-stage, BuildKit e multiplataforma"
        },
        {
          "key": "containers/armazenamento",
          "title": "Armazenamento: camada gravável, volumes e bind mounts"
        },
        {
          "key": "containers/redes",
          "title": "Redes de containers"
        },
        {
          "key": "containers/docker-compose",
          "title": "Docker Compose: aplicações com vários containers"
        },
        {
          "key": "containers/seguranca-e-recursos",
          "title": "Segurança e limites de recursos"
        },
        {
          "key": "containers/de-docker-para-kubernetes",
          "title": "De Docker para Kubernetes"
        }
      ]
    },
    {
      "id": "fundamentos",
      "title": "Fundamentos",
      "lessons": [
        {
          "key": "fundamentos/o-que-e-kubernetes",
          "title": "O que é Kubernetes?"
        },
        {
          "key": "fundamentos/arquitetura",
          "title": "Arquitetura do cluster"
        },
        {
          "key": "fundamentos/kubectl-e-yaml",
          "title": "kubectl e manifestos YAML"
        },
        {
          "key": "fundamentos/laboratorio-kubectl",
          "title": "Laboratório: kubectl na prática"
        }
      ]
    },
    {
      "id": "workloads",
      "title": "Workloads",
      "lessons": [
        {
          "key": "workloads/pods",
          "title": "Pods"
        },
        {
          "key": "workloads/deployments",
          "title": "ReplicaSets e Deployments"
        },
        {
          "key": "workloads/rolling-update",
          "title": "Rolling updates e rollback"
        },
        {
          "key": "workloads/outros-controladores",
          "title": "StatefulSet, DaemonSet, Job e CronJob"
        }
      ]
    },
    {
      "id": "rede",
      "title": "Rede",
      "lessons": [
        {
          "key": "rede/services",
          "title": "Services"
        },
        {
          "key": "rede/ingress",
          "title": "Ingress e Gateway API"
        },
        {
          "key": "rede/dns-networkpolicy",
          "title": "DNS e NetworkPolicy"
        }
      ]
    },
    {
      "id": "gateway-api",
      "title": "Gateway API",
      "lessons": [
        {
          "key": "gateway-api/conceitos",
          "title": "Gateway API: conceitos e papéis"
        },
        {
          "key": "gateway-api/roteamento-httproute",
          "title": "Roteamento com HTTPRoute"
        },
        {
          "key": "gateway-api/listeners-tls-namespaces",
          "title": "Listeners, TLS e rotas entre namespaces"
        },
        {
          "key": "gateway-api/migrando-do-ingress",
          "title": "Migrando do Ingress"
        }
      ]
    },
    {
      "id": "config",
      "title": "Configuração e Armazenamento",
      "lessons": [
        {
          "key": "config/configmaps-secrets",
          "title": "ConfigMaps e Secrets"
        },
        {
          "key": "config/volumes",
          "title": "Volumes, PV, PVC e StorageClass"
        }
      ]
    },
    {
      "id": "scheduling",
      "title": "Recursos e Scheduling",
      "lessons": [
        {
          "key": "scheduling/recursos",
          "title": "Requests, limits e QoS"
        },
        {
          "key": "scheduling/probes",
          "title": "Probes e ciclo de vida"
        },
        {
          "key": "scheduling/hpa",
          "title": "Autoscaling (HPA, VPA, Cluster Autoscaler)"
        },
        {
          "key": "scheduling/afinidade-taints",
          "title": "Afinidade, taints e tolerations"
        }
      ]
    },
    {
      "id": "operacao",
      "title": "Operação e Segurança",
      "lessons": [
        {
          "key": "operacao/namespaces-rbac",
          "title": "Namespaces e RBAC"
        },
        {
          "key": "operacao/troubleshooting",
          "title": "Troubleshooting"
        },
        {
          "key": "operacao/helm",
          "title": "Helm e Kustomize"
        }
      ]
    },
    {
      "id": "helm",
      "title": "Helm do zero à produção",
      "lessons": [
        {
          "key": "helm/introducao",
          "title": "Helm: conceitos e ciclo de vida"
        },
        {
          "key": "helm/anatomia-chart",
          "title": "Anatomia de um chart"
        },
        {
          "key": "helm/values",
          "title": "Values e precedência"
        },
        {
          "key": "helm/templates",
          "title": "Templates: Go templates e Sprig"
        },
        {
          "key": "helm/helpers-e-labels",
          "title": "Helpers, nomes e labels"
        },
        {
          "key": "helm/dependencias",
          "title": "Dependências e subcharts"
        },
        {
          "key": "helm/hooks-e-testes",
          "title": "Hooks e testes"
        },
        {
          "key": "helm/repositorios-e-versoes",
          "title": "Repositórios, OCI e versões"
        },
        {
          "key": "helm/producao",
          "title": "Helm em produção"
        }
      ]
    },
    {
      "id": "troubleshooting",
      "title": "Troubleshooting em Kubernetes",
      "lessons": [
        {
          "key": "troubleshooting/metodologia",
          "title": "Método de investigação"
        },
        {
          "key": "troubleshooting/pods-e-containers",
          "title": "Pods e containers: estados e exit codes"
        },
        {
          "key": "troubleshooting/scheduling",
          "title": "Pods Pending e o scheduler"
        },
        {
          "key": "troubleshooting/rede-e-dns",
          "title": "Rede e DNS: salto a salto"
        },
        {
          "key": "troubleshooting/nos-e-kubelet",
          "title": "Nós e kubelet"
        },
        {
          "key": "troubleshooting/armazenamento",
          "title": "Armazenamento: PVCs, attach e mount"
        },
        {
          "key": "troubleshooting/plano-de-controle",
          "title": "Plano de controle"
        },
        {
          "key": "troubleshooting/ferramentas",
          "title": "Ferramentas e observabilidade"
        }
      ]
    },
    {
      "id": "operators",
      "title": "CRDs e Operators com Kopf",
      "lessons": [
        {
          "key": "operators/fundamentos",
          "title": "Extensões da API e o padrão Operator"
        },
        {
          "key": "operators/anatomia-crd",
          "title": "Anatomia de um CRD"
        },
        {
          "key": "operators/validacao",
          "title": "Schemas, validação e CEL"
        },
        {
          "key": "operators/status-e-condicoes",
          "title": "Status, subrecursos e condições"
        },
        {
          "key": "operators/kopf-primeiros-passos",
          "title": "Primeiro operator com Kopf"
        },
        {
          "key": "operators/kopf-erros-e-retentativas",
          "title": "Kopf: erros, retentativas, timers e daemons"
        },
        {
          "key": "operators/finalizers-e-filhos",
          "title": "Finalizers, ownerReferences e garbage collection"
        },
        {
          "key": "operators/versionamento",
          "title": "Versionamento e conversão"
        },
        {
          "key": "operators/producao",
          "title": "Operator em produção"
        }
      ]
    },
    {
      "id": "pentest",
      "title": "Pentest em Kubernetes",
      "lessons": [
        {
          "key": "pentest/metodologia-e-escopo",
          "title": "Metodologia e escopo"
        },
        {
          "key": "pentest/reconhecimento",
          "title": "Reconhecimento: mapeando a superfície"
        },
        {
          "key": "pentest/acesso-anonimo",
          "title": "Avaliando acesso não autenticado"
        },
        {
          "key": "pentest/enumeracao-com-credenciais",
          "title": "Enumeração com credenciais"
        },
        {
          "key": "pentest/escalada-rbac",
          "title": "Caminhos de escalada de privilégio"
        },
        {
          "key": "pentest/workloads-perigosos",
          "title": "Avaliando workloads perigosos"
        },
        {
          "key": "pentest/movimento-lateral",
          "title": "Movimento lateral e rede"
        },
        {
          "key": "pentest/segredos-e-dados",
          "title": "Descoberta de segredos e dados sensíveis"
        },
        {
          "key": "pentest/ferramentas",
          "title": "Ferramentas e laboratório"
        },
        {
          "key": "pentest/relatorio-e-remediacao",
          "title": "Relatório, priorização e remediação"
        }
      ]
    },
    {
      "id": "hardening",
      "title": "Hardening em Kubernetes",
      "lessons": [
        {
          "key": "hardening/modelo-de-ameacas",
          "title": "Modelo de ameaças e defesa em profundidade"
        },
        {
          "key": "hardening/control-plane-e-kubelet",
          "title": "Hardening do control plane, kubelet e etcd"
        },
        {
          "key": "hardening/rbac-menor-privilegio",
          "title": "RBAC: menor privilégio e caminhos de escalada"
        },
        {
          "key": "hardening/service-accounts-e-tokens",
          "title": "ServiceAccounts, tokens e identidade de workloads"
        },
        {
          "key": "hardening/pod-security",
          "title": "Pod Security: Standards, Admission e securityContext"
        },
        {
          "key": "hardening/rede-zero-trust",
          "title": "Rede: segmentação e zero trust"
        },
        {
          "key": "hardening/segredos-e-criptografia",
          "title": "Segredos e criptografia"
        },
        {
          "key": "hardening/supply-chain",
          "title": "Cadeia de suprimentos: imagens confiáveis"
        },
        {
          "key": "hardening/runtime-e-deteccao",
          "title": "Segurança em runtime: isolamento e detecção"
        },
        {
          "key": "hardening/auditoria-e-resposta",
          "title": "Auditoria, conformidade e resposta a incidentes"
        }
      ]
    }
  ],
  "cases": [
    {
      "id": "crashloop-config",
      "title": "CrashLoopBackOff logo após o deploy"
    },
    {
      "id": "oomkilled-java",
      "title": "OOMKilled intermitente em uma aplicação Java"
    },
    {
      "id": "pods-pending",
      "title": "Pods Pending com o cluster \"vazio\""
    },
    {
      "id": "service-sem-endpoints",
      "title": "503 no Ingress depois de \"padronizar os labels\""
    },
    {
      "id": "dns-lento",
      "title": "Latências de exatamente 5 segundos"
    },
    {
      "id": "imagepullbackoff",
      "title": "ImagePullBackOff só em produção"
    },
    {
      "id": "disk-pressure",
      "title": "Pods Evicted e nó com DiskPressure"
    },
    {
      "id": "cpu-throttling",
      "title": "API lenta com CPU \"sobrando\""
    },
    {
      "id": "erros-502-no-deploy",
      "title": "Pico de 502 a cada deploy"
    },
    {
      "id": "drain-travado-pdb",
      "title": "Upgrade do cluster travado no drain"
    },
    {
      "id": "gateway-rota-nao-anexada",
      "title": "HTTPRoute criada, mas o site responde 404"
    },
    {
      "id": "gateway-backend-outro-namespace",
      "title": "Checkout respondendo 500 depois da migração"
    },
    {
      "id": "gateway-hostname-sem-intersecao",
      "title": "Um domínio antigo que o Gateway ignora"
    },
    {
      "id": "rbac-apigroup-errado",
      "title": "Pipeline proibido de atualizar Deployments"
    },
    {
      "id": "rbac-logs-exec-proibidos",
      "title": "O suporte vê os Pods, mas não consegue ler logs"
    },
    {
      "id": "rbac-serviceaccount-superpoderosa",
      "title": "Uma aplicação invadida lendo Secrets do cluster todo"
    },
    {
      "id": "helm-operacao-em-andamento",
      "title": "\"another operation is in progress\" em todo deploy"
    },
    {
      "id": "helm-listas-substituidas",
      "title": "A API parou de achar o banco depois de \"só mudar o log\""
    },
    {
      "id": "helm-numeros-em-values",
      "title": "A imagem 2.0240501e+07 não existe"
    },
    {
      "id": "helm-recurso-sem-dono",
      "title": "\"invalid ownership metadata\" ao migrar para Helm"
    },
    {
      "id": "helm-selector-imutavel",
      "title": "Upgrade do chart 2.0 falha com \"field is immutable\""
    },
    {
      "id": "helm-crds-nao-atualizam",
      "title": "O operador novo não aceita os recursos novos"
    },
    {
      "id": "helm-hook-job-ja-existe",
      "title": "Deploy bloqueado por um Job de migração que \"já existe\""
    },
    {
      "id": "helm-config-sem-rollout",
      "title": "Mudei a configuração pelo Helm e nada mudou"
    },
    {
      "id": "helm-nome-maior-que-63",
      "title": "Ambiente efêmero falha por causa do nome da branch"
    },
    {
      "id": "helm-senha-postgres-reinstalacao",
      "title": "Depois de reinstalar, a aplicação não autentica no PostgreSQL"
    },
    {
      "id": "helm-hpa-resetado-no-deploy",
      "title": "Cada deploy derruba a capacidade durante o pico"
    },
    {
      "id": "helm-dependencia-faltando",
      "title": "O pipeline passou a falhar depois de adicionar o Redis"
    },
    {
      "id": "ts-no-notready-containerd",
      "title": "Um nó NotReady que \"está ligado\""
    },
    {
      "id": "ts-namespace-terminating",
      "title": "Namespace preso em Terminating há dois dias"
    },
    {
      "id": "ts-multi-attach",
      "title": "O CMS não volta depois que o nó morreu"
    },
    {
      "id": "ts-pod-preso-terminating",
      "title": "Pods que não terminam de terminar"
    },
    {
      "id": "ts-liveness-sob-carga",
      "title": "A cada pico de tráfego, todos os Pods reiniciam"
    },
    {
      "id": "ts-coredns-loop",
      "title": "CoreDNS em CrashLoopBackOff num cluster novo"
    },
    {
      "id": "ts-webhook-fora-do-ar",
      "title": "Ninguém consegue fazer deploy: \"failed calling webhook\""
    },
    {
      "id": "ts-certificados-expirados",
      "title": "Na segunda-feira, o kubectl parou de funcionar"
    },
    {
      "id": "ts-conntrack-cheio",
      "title": "Timeouts aleatórios só nos nós do gateway"
    },
    {
      "id": "ts-ips-esgotados",
      "title": "Pods novos presos em ContainerCreating com o cluster \"vazio\""
    },
    {
      "id": "op-campos-sumindo",
      "title": "O backup configurado que nunca rodou"
    },
    {
      "id": "op-status-ignorado",
      "title": "O status que não muda nunca"
    },
    {
      "id": "op-loop-de-reconcile",
      "title": "O operador que conversa sozinho"
    },
    {
      "id": "op-finalizer-orfao",
      "title": "Bancos que não morrem"
    },
    {
      "id": "op-crd-apagada",
      "title": "Um helm uninstall apagou todos os certificados"
    },
    {
      "id": "op-rbac-forbidden",
      "title": "O operador em produção que não faz nada"
    },
    {
      "id": "op-duas-replicas",
      "title": "Cada banco novo aparece duas vezes na nuvem"
    },
    {
      "id": "op-webhook-conversao",
      "title": "kubectl get databases parou de funcionar"
    },
    {
      "id": "op-stored-versions",
      "title": "Não consigo remover a versão v1alpha1"
    },
    {
      "id": "op-handler-nao-idempotente",
      "title": "Handler preso em 409 AlreadyExists"
    },
    {
      "id": "op-filhos-orfaos",
      "title": "Deployments fantasmas depois de apagar os CRs"
    },
    {
      "id": "op-observed-generation",
      "title": "O pipeline disse \"deploy concluído\" — e não estava"
    },
    {
      "id": "ct-latest-mudou",
      "title": "Mesma imagem, comportamentos diferentes"
    },
    {
      "id": "ct-imagem-gigante",
      "title": "A imagem de 2,3 GB que atrasa o autoscaling"
    },
    {
      "id": "ct-segredo-na-imagem",
      "title": "A chave da nuvem que estava na imagem pública"
    },
    {
      "id": "ct-localhost-no-container",
      "title": "Funciona com npm run dev, não funciona no container"
    },
    {
      "id": "ct-sigterm-ignorado",
      "title": "Todo deploy derruba requisições em andamento"
    },
    {
      "id": "ct-dados-perdidos",
      "title": "O banco que voltou vazio depois da atualização"
    },
    {
      "id": "ct-permissao-volume",
      "title": "Permission denied ao gravar uploads"
    },
    {
      "id": "ct-exec-format-error",
      "title": "exec format error só no servidor"
    },
    {
      "id": "ct-depends-on",
      "title": "A API sobe antes do banco e morre"
    },
    {
      "id": "ct-oom-137",
      "title": "O serviço Java que some sem deixar erro"
    },
    {
      "id": "ct-cache-invalidado",
      "title": "Todo build reinstala todas as dependências"
    },
    {
      "id": "ct-disco-cheio",
      "title": "O servidor de CI sem espaço em disco"
    },
    {
      "id": "hd-dashboard-exposto",
      "title": "O Dashboard que minerava criptomoedas"
    },
    {
      "id": "hd-kubelet-anonimo",
      "title": "Comandos em containers sem passar pelo API server"
    },
    {
      "id": "hd-cni-sem-networkpolicy",
      "title": "As NetworkPolicies que nunca funcionaram"
    },
    {
      "id": "hd-pod-privilegiado-escape",
      "title": "O Pod de \"debug\" que era dono do nó"
    },
    {
      "id": "hd-token-vazado",
      "title": "O token do CI que nunca expira"
    },
    {
      "id": "hd-create-pods-escalada",
      "title": "\"Os devs não podem ler Secrets\" — mas podiam"
    },
    {
      "id": "hd-secrets-em-backup",
      "title": "O backup do etcd no bucket errado"
    },
    {
      "id": "hd-imagem-typosquatting",
      "title": "Um \"nginx\" que não era o nginx"
    },
    {
      "id": "hd-auditoria-sem-registro",
      "title": "O incidente que ninguém conseguiu reconstruir"
    },
    {
      "id": "hd-egress-exfiltracao",
      "title": "Dados saindo por onde ninguém olhava"
    },
    {
      "id": "hd-exec-sem-deteccao",
      "title": "Shells em produção que ninguém via"
    },
    {
      "id": "hd-impersonate",
      "title": "A ferramenta de suporte que podia ser qualquer um"
    },
    {
      "id": "pt-api-anonimo",
      "title": "API respondendo sem credencial"
    },
    {
      "id": "pt-kubelet-exec",
      "title": "kubelet aceita acesso não autenticado"
    },
    {
      "id": "pt-token-exposto",
      "title": "Token de aplicação com permissões amplas"
    },
    {
      "id": "pt-rbac-escalada",
      "title": "De dev a cluster-admin"
    },
    {
      "id": "pt-pod-privilegiado",
      "title": "Namespace sem Pod Security"
    },
    {
      "id": "pt-secrets-acessiveis",
      "title": "Credenciais de banco a um curl de distância"
    },
    {
      "id": "pt-registry-aberto",
      "title": "Registro de imagens sem autenticação"
    },
    {
      "id": "pt-etcd-exposto",
      "title": "etcd alcançável a partir dos nós"
    },
    {
      "id": "pt-sem-segmentacao",
      "title": "Rede plana entre namespaces"
    },
    {
      "id": "pt-sa-default",
      "title": "A ServiceAccount default com poderes"
    },
    {
      "id": "pt-dashboard",
      "title": "Dashboard publicado sem autenticação"
    },
    {
      "id": "pt-ci-comprometido",
      "title": "Credenciais de deploy amplas no CI"
    }
  ],
  "simulators": [
    {
      "id": "terminal",
      "title": "Terminal kubectl"
    },
    {
      "id": "deployment",
      "title": "Self-healing"
    },
    {
      "id": "rolling-update",
      "title": "Rolling update"
    },
    {
      "id": "service",
      "title": "Service e endpoints"
    },
    {
      "id": "scheduler",
      "title": "Scheduler"
    },
    {
      "id": "hpa",
      "title": "HPA"
    },
    {
      "id": "network-policy",
      "title": "NetworkPolicy"
    },
    {
      "id": "gateway-api",
      "title": "Gateway API"
    },
    {
      "id": "rbac-lab",
      "title": "RBAC: menor privilégio"
    },
    {
      "id": "rbac",
      "title": "RBAC (auth can-i)"
    },
    {
      "id": "drain-pdb",
      "title": "Drain e PDB"
    },
    {
      "id": "qos",
      "title": "QoS e despejo"
    },
    {
      "id": "storage",
      "title": "PV, PVC e StorageClass"
    },
    {
      "id": "ingress",
      "title": "Roteamento de Ingress"
    },
    {
      "id": "dns",
      "title": "DNS e ndots"
    },
    {
      "id": "statefulset",
      "title": "StatefulSet"
    },
    {
      "id": "cronjob",
      "title": "CronJob e Jobs"
    },
    {
      "id": "cluster-autoscaler",
      "title": "Cluster Autoscaler"
    },
    {
      "id": "helm-release",
      "title": "Helm: ciclo de vida"
    },
    {
      "id": "helm-lint",
      "title": "Helm: anatomia e lint"
    },
    {
      "id": "helm-values",
      "title": "Helm: merge de values"
    },
    {
      "id": "helm-template",
      "title": "Helm: templates"
    },
    {
      "id": "helm-helpers",
      "title": "Helm: nomes, labels e checksum"
    },
    {
      "id": "helm-dependencies",
      "title": "Helm: dependências"
    },
    {
      "id": "helm-hooks",
      "title": "Helm: hooks e testes"
    },
    {
      "id": "helm-semver",
      "title": "Helm: versões e restrições"
    },
    {
      "id": "helm-upgrade",
      "title": "Helm: three-way merge"
    },
    {
      "id": "ts-diagnosis",
      "title": "Árvore de diagnóstico"
    },
    {
      "id": "ts-exit-code",
      "title": "Decodificador de exit codes"
    },
    {
      "id": "ts-scheduling",
      "title": "Por que o Pod está Pending?"
    },
    {
      "id": "ts-network-path",
      "title": "Caminho da requisição"
    },
    {
      "id": "ts-node",
      "title": "Nó em apuros"
    },
    {
      "id": "ts-volume",
      "title": "PVC e volumes"
    },
    {
      "id": "ts-control-plane",
      "title": "Control plane sob falha"
    },
    {
      "id": "ts-tools",
      "title": "Qual ferramenta usar?"
    },
    {
      "id": "op-reconcile",
      "title": "Loop de reconciliação"
    },
    {
      "id": "op-crd-builder",
      "title": "Montador de CRD"
    },
    {
      "id": "op-schema",
      "title": "Schema e CEL"
    },
    {
      "id": "op-status",
      "title": "Status e observedGeneration"
    },
    {
      "id": "op-kopf-handlers",
      "title": "Kopf: quais handlers disparam"
    },
    {
      "id": "op-kopf-retries",
      "title": "Kopf: erros e retentativas"
    },
    {
      "id": "op-finalizers",
      "title": "Finalizers e garbage collection"
    },
    {
      "id": "op-versions",
      "title": "Versões e conversão de CRD"
    },
    {
      "id": "op-rbac",
      "title": "Operator em produção"
    },
    {
      "id": "hd-attack-path",
      "title": "Cadeia de ataque"
    },
    {
      "id": "hd-cis-audit",
      "title": "Auditoria CIS do control plane"
    },
    {
      "id": "hd-rbac-risk",
      "title": "Risco de permissões RBAC"
    },
    {
      "id": "hd-token",
      "title": "Tokens de ServiceAccount"
    },
    {
      "id": "hd-pss",
      "title": "Pod Security Admission"
    },
    {
      "id": "hd-netpol-matrix",
      "title": "Zero trust com NetworkPolicy"
    },
    {
      "id": "hd-secrets",
      "title": "Vetores de vazamento de Secrets"
    },
    {
      "id": "hd-admission",
      "title": "Políticas de imagem (supply chain)"
    },
    {
      "id": "hd-runtime",
      "title": "Runtime: prevenir × detectar"
    },
    {
      "id": "hd-audit-policy",
      "title": "Política de auditoria"
    },
    {
      "id": "pt-scope",
      "title": "Regras de engajamento"
    },
    {
      "id": "pt-recon",
      "title": "Recon externo"
    },
    {
      "id": "pt-anon",
      "title": "Acesso anônimo"
    },
    {
      "id": "pt-enum",
      "title": "Enumeração com token"
    },
    {
      "id": "pt-privesc",
      "title": "Caminho de escalada"
    },
    {
      "id": "pt-workload",
      "title": "Blast radius do workload"
    },
    {
      "id": "pt-lateral",
      "title": "Movimento lateral"
    },
    {
      "id": "pt-loot",
      "title": "Descoberta de dados sensíveis"
    },
    {
      "id": "pt-tools",
      "title": "Ferramentas de avaliação"
    },
    {
      "id": "pt-report",
      "title": "Relatório e priorização"
    },
    {
      "id": "pod-lifecycle",
      "title": "Ciclo de vida e falhas"
    }
  ]
} as const;
