import type { SimulatorId } from '../../types';

export interface SimulatorInfo {
  id: SimulatorId;
  title: string;
  emoji: string;
  description: string;
}

export const simulators: SimulatorInfo[] = [
  { id: 'terminal', title: 'Terminal kubectl', emoji: '⌨️', description: '23 missões em cinco níveis: opere um cluster com 1 control-plane e 2 workers, de Pods a troubleshooting e operação avançada.' },
  { id: 'deployment', title: 'Self-healing', emoji: '♻️', description: 'Mate Pods, derrube nós e mude réplicas: veja o ReplicaSet e o scheduler reconciliarem o estado.' },
  { id: 'rolling-update', title: 'Rolling update', emoji: '🚀', description: 'Ajuste maxSurge e maxUnavailable, faça deploy de uma versão quebrada e execute o rollback.' },
  { id: 'service', title: 'Service e endpoints', emoji: '🔀', description: 'Envie requisições e veja o balanceamento. Remova labels ou quebre a readiness e observe os endpoints.' },
  { id: 'scheduler', title: 'Scheduler', emoji: '🧩', description: 'Crie Pods com requests diferentes, taints e tolerations. Veja filtragem, pontuação e Pods Pending.' },
  { id: 'hpa', title: 'HPA', emoji: '📈', description: 'Aumente a carga e acompanhe o Horizontal Pod Autoscaler calcular réplicas com a fórmula real.' },
  { id: 'network-policy', title: 'NetworkPolicy', emoji: '🛡️', description: 'Ligue e desligue policies e veja, conexão a conexão, o que é liberado ou bloqueado — inclusive o DNS.' },
  { id: 'gateway-api', title: 'Gateway API', emoji: '🚪', description: 'Gateway com listeners e allowedRoutes, HTTPRoutes com matches, filtros e canary por peso, ReferenceGrant e condições de status.' },
  { id: 'rbac-lab', title: 'RBAC: menor privilégio', emoji: '🧑‍🔧', description: 'Monte Roles para cumprir missões reais — com subrecursos, apiGroups e o mínimo de permissões.' },
  { id: 'rbac', title: 'RBAC (auth can-i)', emoji: '🔐', description: 'Monte Roles e bindings e descubra quem pode fazer o quê, em qual namespace, e por quê.' },
  { id: 'drain-pdb', title: 'Drain e PDB', emoji: '🔧', description: 'Drene nós para manutenção e veja o PodDisruptionBudget segurar (ou travar) as evictions.' },
  { id: 'qos', title: 'QoS e despejo', emoji: '⚖️', description: 'Ajuste requests, limits e uso de memória: veja a classe de QoS, OOMKilled e a ordem de despejo do kubelet.' },
  { id: 'storage', title: 'PV, PVC e StorageClass', emoji: '💾', description: 'Crie PVCs e veja o bind com PVs estáticos, o provisionamento dinâmico e o reclaimPolicy.' },
  { id: 'ingress', title: 'Roteamento de Ingress', emoji: '🌐', description: 'Edite regras de host e path (Prefix e Exact) e descubra qual backend atende cada URL.' },
  { id: 'dns', title: 'DNS e ndots', emoji: '📖', description: 'Veja cada consulta que o Pod faz ao resolver um nome, e por que ndots:5 multiplica o tráfego DNS.' },
  { id: 'statefulset', title: 'StatefulSet', emoji: '🗄️', description: 'Escale e mate Pods: nomes ordinais, ordem de criação e PVCs que sobrevivem aos Pods.' },
  { id: 'cronjob', title: 'CronJob e Jobs', emoji: '⏰', description: 'Um relógio acelerado com Allow, Forbid e Replace, retentativas (backoffLimit) e histórico.' },
  { id: 'cluster-autoscaler', title: 'Cluster Autoscaler', emoji: '🏗️', description: 'Pods Pending disparam novos nós; nós ociosos são removidos — a menos que algo impeça.' },
  { id: 'helm-release', title: 'Helm: ciclo de vida', emoji: '📦', description: 'install, upgrade, rollback e uninstall com histórico, status, Secrets de revisão, --atomic e a trava de operação pendente.' },
  { id: 'helm-lint', title: 'Helm: anatomia e lint', emoji: '🧾', description: 'Explore a estrutura de um chart e provoque erros clássicos para ver as mensagens reais do helm lint.' },
  { id: 'helm-values', title: 'Helm: merge de values', emoji: '🧮', description: 'Combine values.yaml, -f, --set e --set-string e veja o resultado, a origem e o tipo Go de cada chave.' },
  { id: 'helm-template', title: 'Helm: templates', emoji: '🧩', description: 'Um motor de Go templates + Sprig no navegador: edite template e values e veja o manifesto ou o erro.' },
  { id: 'helm-helpers', title: 'Helm: nomes, labels e checksum', emoji: '🏷️', description: 'Calcule o fullname (limite de 63), os labels padrão e veja o checksum decidir se os Pods reiniciam.' },
  { id: 'helm-dependencies', title: 'Helm: dependências', emoji: '🔗', description: 'condition, tags, alias e globals: quais subcharts são renderizados e quais values cada um enxerga.' },
  { id: 'helm-hooks', title: 'Helm: hooks e testes', emoji: '🪝', description: 'Fases, pesos, políticas de deleção, hooks que falham e o que sobra no cluster.' },
  { id: 'helm-semver', title: 'Helm: versões e restrições', emoji: '🔢', description: 'Qual versão ~, ^, x, intervalos e prereleases escolhem numa lista de versões publicadas.' },
  { id: 'helm-upgrade', title: 'Helm: three-way merge', emoji: '🔄', description: 'Drift, HPA e sidecars: compare o upgrade do Helm 3+ (3-way) com o do Helm 2 (2-way).' },
  { id: 'ts-diagnosis', title: 'Árvore de diagnóstico', emoji: '🧭', description: 'Do sintoma (STATUS do Pod) à causa provável e aos comandos certos.' },
  { id: 'ts-exit-code', title: 'Decodificador de exit codes', emoji: '🔢', description: 'Exit codes, sinais e o backoff exponencial do CrashLoopBackOff.' },
  { id: 'ts-scheduling', title: 'Por que o Pod está Pending?', emoji: '📌', description: 'Monte a mensagem FailedScheduling nó a nó: recursos, taints, selectors, cordon.' },
  { id: 'ts-network-path', title: 'Caminho da requisição', emoji: '🛰️', description: 'Injete falhas em DNS, Service, endpoints, NetworkPolicy e veja o sintoma no cliente.' },
  { id: 'ts-node', title: 'Nó em apuros', emoji: '🖥️', description: 'Linha do tempo de um nó com kubelet, rede, runtime ou disco com problemas.' },
  { id: 'ts-volume', title: 'PVC e volumes', emoji: '💾', description: 'StorageClass, provisioner, Multi-Attach, permissões e quotas.' },
  { id: 'ts-control-plane', title: 'Control plane sob falha', emoji: '🏛️', description: 'Derrube API server, etcd, scheduler, webhooks e veja o que ainda funciona.' },
  { id: 'ts-tools', title: 'Qual ferramenta usar?', emoji: '🧰', description: '10 missões: escolha o comando certo para cada situação.' },
  { id: 'op-reconcile', title: 'Loop de reconciliação', emoji: '🔁', description: 'Estado desejado × real: drift, eventos perdidos e convergência level-triggered.' },
  { id: 'op-crd-builder', title: 'Montador de CRD', emoji: '🧩', description: 'Grupo, nomes, escopo e versão: YAML, endpoints REST e erros de validação do CRD.' },
  { id: 'op-schema', title: 'Schema e CEL', emoji: '📐', description: 'Edite um CR em YAML e veja pruning, defaults, validação OpenAPI e regras CEL.' },
  { id: 'op-status', title: 'Status e observedGeneration', emoji: '🚦', description: 'generation × observedGeneration, condições e o subrecurso /status.' },
  { id: 'op-kopf-handlers', title: 'Kopf: quais handlers disparam', emoji: '🐍', description: 'create, update, field, delete, resume e event para cada acontecimento.' },
  { id: 'op-kopf-retries', title: 'Kopf: erros e retentativas', emoji: '🔄', description: 'TemporaryError, PermanentError, backoff, retries e idempotência.' },
  { id: 'op-finalizers', title: 'Finalizers e garbage collection', emoji: '🗑️', description: 'Apague um CR: finalizer, on.delete, ownerReferences e --cascade.' },
  { id: 'op-versions', title: 'Versões e conversão de CRD', emoji: '🔀', description: 'served, storage, storedVersions e webhook de conversão.' },
  { id: 'op-rbac', title: 'Operator em produção', emoji: '🛡️', description: 'RBAC mínimo do Kopf, escopo, réplicas e peering.' },
  { id: 'hd-attack-path', title: 'Cadeia de ataque', emoji: '🎯', description: 'Do RCE à conta de nuvem: ligue defesas em profundidade e veja onde o ataque para ou é detectado.' },
  { id: 'hd-cis-audit', title: 'Auditoria CIS do control plane', emoji: '📋', description: 'Flags do API server, kubelet e etcd avaliadas no estilo kube-bench, com correções.' },
  { id: 'hd-rbac-risk', title: 'Risco de permissões RBAC', emoji: '🧨', description: 'Quais verbos e recursos permitem escalar até cluster-admin.' },
  { id: 'hd-token', title: 'Tokens de ServiceAccount', emoji: '🎫', description: 'Token legado × projetado, automount, expiração e audiência: o que um token roubado permite.' },
  { id: 'hd-pss', title: 'Pod Security Admission', emoji: '🚧', description: 'Avalie um Pod contra baseline e restricted com as mensagens reais do PSA.' },
  { id: 'hd-netpol-matrix', title: 'Zero trust com NetworkPolicy', emoji: '🕸️', description: 'Matriz de conectividade com DNS, internet e o metadata da nuvem.' },
  { id: 'hd-secrets', title: 'Vetores de vazamento de Secrets', emoji: '🔐', description: 'Criptografia em repouso, backups, RBAC, env, logs e Git.' },
  { id: 'hd-admission', title: 'Políticas de imagem (supply chain)', emoji: '📦', description: 'Registries permitidos, assinatura cosign, digest e CVEs em Enforce ou Audit.' },
  { id: 'hd-runtime', title: 'Runtime: prevenir × detectar', emoji: '👁️', description: 'Ações de um invasor no container contra seccomp, capabilities, read-only, egress e Falco.' },
  { id: 'hd-audit-policy', title: 'Política de auditoria', emoji: '📜', description: 'Regras em ordem, níveis None/Metadata/Request/RequestResponse e o que cada requisição registra.' },
  { id: 'pt-scope', title: 'Regras de engajamento', emoji: '📝', description: 'Autorização, escopo e janela: a ação de teste está permitida?' },
  { id: 'pt-recon', title: 'Recon externo', emoji: '🔭', description: 'Superfície exposta do cluster e o que cada porta revela ao avaliador.' },
  { id: 'pt-anon', title: 'Acesso anônimo', emoji: '👻', description: 'O que system:anonymous/unauthenticated alcançam sem credencial.' },
  { id: 'pt-enum', title: 'Enumeração com token', emoji: '🔎', description: 'A partir do que um token permite, o que a avaliação revela e o próximo passo.' },
  { id: 'pt-privesc', title: 'Caminho de escalada', emoji: '🧗', description: 'Do ponto de partida até cluster-admin, e qual controle rompe o caminho.' },
  { id: 'pt-workload', title: 'Blast radius do workload', emoji: '💥', description: 'Quais campos do Pod ampliam o alcance de um comprometimento.' },
  { id: 'pt-lateral', title: 'Movimento lateral', emoji: '↔️', description: 'O que se alcança na rede a partir de um Pod comprometido.' },
  { id: 'pt-loot', title: 'Descoberta de dados sensíveis', emoji: '💎', description: 'Esconderijos comuns de segredos e como fechar cada um.' },
  { id: 'pt-tools', title: 'Ferramentas de avaliação', emoji: '🧰', description: 'Qual ferramenta para cada tarefa de pentest — sempre com autorização.' },
  { id: 'pt-report', title: 'Relatório e priorização', emoji: '📊', description: 'Ordene achados por risco (probabilidade × impacto) e proponha correções.' },
  { id: 'pod-lifecycle', title: 'Ciclo de vida e falhas', emoji: '🩺', description: 'Provoque CrashLoopBackOff, OOMKilled, ImagePullBackOff e falhas de probes, e leia os eventos.' },
];
